<a href="https://colab.research.google.com/github/Cmamta03/6-month-bootcamp_-agentic-genai-ai-fsds-ml-with-python.git-/blob/main/spotify.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import os
for dirname,  _, filenames in os.walk('/kaggle/input'):
  for filename in filenames:
    print(os.path.join(dirname, filename))

In [21]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/spotify_data clean.csv")
df

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8577,0AQquaENerGps8BQmbPw14,Big Iron,1,71,False,Marty Robbins,60,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,3.92
8578,4f8hBeMXMvssn6HtFAtblo,El Paso,10,64,False,Marty Robbins,61,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,4.32
8579,0Vy7wsXNFrbNc6UTWoScnM,Over the Rainbow,5,8,False,The Mystics,27,18184,doo-wop,2ifB9Xjp9DdpqLlYlY60QW,Presenting The Mystics,1959-02-11,9,compilation,2.28
8580,760clbeDBWmBsBLbszWuNZ,I'm A Man,2,55,False,Bo Diddley,44,333376,"blues, classic blues, rock and roll, rockabilly",1cbtDEwxCjMhglb49OgNBR,Bo Diddley,1958-01-01,12,album,2.74
8581,61GEP8lryEfcuEgBMbRmNi,Alone And Forsaken,11,45,False,Hank Williams,55,1067339,"classic country, honky tonk, traditional count...",3cusZESjkIDnDXyQwbpSsT,Moanin' The Blues (Expanded Edition),1952-09-12,12,album,2.02

In [22]:
df.head()

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39

In [23]:
df.columns

Index(['track_id', 'track_name', 'track_number', 'track_popularity',
       'explicit', 'artist_name', 'artist_popularity', 'artist_followers',
       'artist_genres', 'album_id', 'album_name', 'album_release_date',
       'album_total_tracks', 'album_type', 'track_duration_min'],
      dtype='object')

In [24]:
df.tail()

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
8577,0AQquaENerGps8BQmbPw14,Big Iron,1,71,False,Marty Robbins,60,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,3.92
8578,4f8hBeMXMvssn6HtFAtblo,El Paso,10,64,False,Marty Robbins,61,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,4.32
8579,0Vy7wsXNFrbNc6UTWoScnM,Over the Rainbow,5,8,False,The Mystics,27,18184,doo-wop,2ifB9Xjp9DdpqLlYlY60QW,Presenting The Mystics,1959-02-11,9,compilation,2.28
8580,760clbeDBWmBsBLbszWuNZ,I'm A Man,2,55,False,Bo Diddley,44,333376,"blues, classic blues, rock and roll, rockabilly",1cbtDEwxCjMhglb49OgNBR,Bo Diddley,1958-01-01,12,album,2.74
8581,61GEP8lryEfcuEgBMbRmNi,Alone And Forsaken,11,45,False,Hank Williams,55,1067339,"classic country, honky tonk, traditional count...",3cusZESjkIDnDXyQwbpSsT,Moanin' The Blues (Expanded Edition),1952-09-12,12,album,2.02

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8582 entries, 0 to 8581
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8582 non-null   object
 1   track_name          8582 non-null   object
 2   track_number        8582 non-null   int64
 3   track_popularity    8582 non-null   int64
 4   explicit            8582 non-null   bool
 5   artist_name         8579 non-null   object
 6   artist_popularity   8582 non-null   int64
 7   artist_followers    8582 non-null   int64
 8   artist_genres       5221 non-null   object
 9   album_id            8582 non-null   object
 10  album_name          8582 non-null   object
 11  album_release_date  8582 non-null   object
 12  album_total_tracks  8582 non-null   int64
 13  album_type          8582 non-null   object
 14  track_duration_min  8582 non-null   float64
dtypes: bool(1), float64(1), int64(5), object(8)
memory usage: 947.2+ KB

In [26]:
df["album_release_date"]=pd.to_datetime(df["album_release_date"], errors='coerce')

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8582 entries, 0 to 8581
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8582 non-null   object
 1   track_name          8582 non-null   object
 2   track_number        8582 non-null   int64
 3   track_popularity    8582 non-null   int64
 4   explicit            8582 non-null   bool
 5   artist_name         8579 non-null   object
 6   artist_popularity   8582 non-null   int64
 7   artist_followers    8582 non-null   int64
 8   artist_genres       5221 non-null   object
 9   album_id            8582 non-null   object
 10  album_name          8582 non-null   object
 11  album_release_date  8582 non-null   datetime64[ns]
 12  album_total_tracks  8582 non-null   int64
 13  album_type          8582 non-null   object
 14  track_duration_min  8582 non-null   float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(5), object(7)
memory usage: 947.2+ KB

In [28]:
df

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8577,0AQquaENerGps8BQmbPw14,Big Iron,1,71,False,Marty Robbins,60,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,3.92
8578,4f8hBeMXMvssn6HtFAtblo,El Paso,10,64,False,Marty Robbins,61,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,4.32
8579,0Vy7wsXNFrbNc6UTWoScnM,Over the Rainbow,5,8,False,The Mystics,27,18184,doo-wop,2ifB9Xjp9DdpqLlYlY60QW,Presenting The Mystics,1959-02-11,9,compilation,2.28
8580,760clbeDBWmBsBLbszWuNZ,I'm A Man,2,55,False,Bo Diddley,44,333376,"blues, classic blues, rock and roll, rockabilly",1cbtDEwxCjMhglb49OgNBR,Bo Diddley,1958-01-01,12,album,2.74
8581,61GEP8lryEfcuEgBMbRmNi,Alone And Forsaken,11,45,False,Hank Williams,55,1067339,"classic country, honky tonk, traditional count...",3cusZESjkIDnDXyQwbpSsT,Moanin' The Blues (Expanded Edition),1952-09-12,12,album,2.02

In [29]:
df.describe()

,track_number,track_popularity,artist_popularity,artist_followers,album_release_date,album_total_tracks,track_duration_min
count,8582.000000,8582.000000,8582.000000,8.582000e+03,8582,8582.000000,8582.000000
mean,5.772547,52.356211,69.730016,2.403472e+07,2015-07-21 16:44:54.756466944,13.789443,3.492805
min,1.000000,0.000000,0.000000,0.000000e+00,1952-09-12 00:00:00,1.000000,0.070000
25%,1.000000,39.000000,60.000000,4.623200e+05,2012-03-12 00:00:00,6.000000,2.880000
50%,4.000000,58.000000,74.000000,6.105547e+06,2018-02-14 00:00:00,13.000000,3.445000
75%,9.000000,71.000000,84.000000,2.725255e+07,2022-07-21 00:00:00,17.000000,3.990000
max,102.000000,99.000000,100.000000,1.455421e+08,2025-10-31 00:00:00,181.000000,13.510000
std,6.052792,23.816076,19.645979,3.803180e+07,NaN,11.887131,1.057970

In [32]:
df.describe(include="O")

,track_id,track_name,artist_name,artist_genres,album_id,album_name,album_type
count,8582,8582,8579,5221,8582,8582,8582
unique,8582,7462,2547,661,5205,4870,3
top,61GEP8lryEfcuEgBMbRmNi,Flowers,Taylor Swift,soundtrack,3FFGbUutKWN1c4f0CJR4Uh,Nevermind (Super Deluxe Edition),album
freq,1,8,324,345,70,70,5856

In [33]:
df.isna().sum()

track_id                 0
track_name               0
track_number             0
track_popularity         0
explicit                 0
artist_name              3
artist_popularity        0
artist_followers         0
artist_genres         3361
album_id                 0
album_name               0
album_release_date       0
album_total_tracks       0
album_type               0
track_duration_min       0
dtype: int64

In [34]:
df1 = df.dropna(subset=["track_name", "artist_name", "album_release_date"])

In [35]:
df1.isna().sum()

track_id                 0
track_name               0
track_number             0
track_popularity         0
explicit                 0
artist_name              0
artist_popularity        0
artist_followers         0
artist_genres         3358
album_id                 0
album_name               0
album_release_date       0
album_total_tracks       0
album_type               0
track_duration_min       0
dtype: int64

In [36]:
df1.duplicated().sum()

np.int64(0)

In [38]:
df1["track_popularity"].agg(["min", "max", "mean"])

min      0.000000
max     99.000000
mean    52.355519
Name: track_popularity, dtype: float64

In [39]:
df1[df1["track_popularity"]==100.000000]

Empty DataFrame
Columns: [track_id, track_name, track_number, track_popularity, explicit, artist_name, artist_popularity, artist_followers, artist_genres, album_id, album_name, album_release_date, album_total_tracks, album_type, track_duration_min]
Index: []

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_0.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['track_number']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'track_number'}, axis=1)
              .sort_values('track_number', ascending=True))
  xs = counted['track_number']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values('track_number', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('track_number')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['track_popularity']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'track_popularity'}, axis=1)
              .sort_values('track_popularity', ascending=True))
  xs = counted['track_popularity']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_2.sort_values('track_popularity', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('track_popularity')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['artist_popularity']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'artist_popularity'}, axis=1)
              .sort_values('artist_popularity', ascending=True))
  xs = counted['artist_popularity']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_3.sort_values('artist_popularity', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('artist_popularity')
_ = plt.ylabel('count()')

In [40]:
df[df["track_popularity"]==0.000000]

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39
13,6zFWxD9hkOPAIlgWAGyQGQ,Let’s Go!!,2,0,True,Ovi Jozi,17,3567,NaN,0liPj9Le4hvoMJQhYOi5kP,"High Risk, High Reward",2025-10-24,6,single,2.05
596,3XbsJyWT7pwLh8XUr2fSOV,Lollapalooza,1,0,False,Daya Blaze,1,0,NaN,6kogtYJA3XQtHP3VDsbbsd,Lollapalooza,2025-04-06,1,single,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8376,7J87u2pUI0xBt8HVKNuJ8n,Yesterday Is Here,7,0,False,Tom Waits,57,1460772,"singer-songwriter, southern gothic",2zIaHUyMLCtg7pxtp1ZpO7,Franks Wild Years,1987-08-17,17,album,2.48
8469,4Anmaai9xAsuhCc6Kl7qWM,Cantina Band,9,0,False,John Williams,70,1605379,soundtrack,1HD2YLgCkCFOSeQRKWXifG,Star Wars: A New Hope (Original Motion Picture...,1977-01-01,16,album,2.78
8492,5EBoNoVE7BoGQ7Hfd2uGUR,Don't Let Me Down - Remastered,5,0,False,The Beatles,82,30714318,"classic rock, psychedelic rock",5UtlwR5GMEM3XrF8GdzMmB,The Beatles 1967 - 1970 (Remastered),1973-04-02,28,compilation,3.59
8561,7hc9InDMML0NwWNPoK49AR,La condanna,22,0,False,Ennio Morricone,65,1324293,soundtrack,0ClQ52I3xdmtOgu8e5djB9,La resa dei conti - The Big Gundown [Bande ori...,1966-06-30,24,album,1.22
8565,4Wzt8Dm4xpO3LjWDecP4bA,She's Not There,7,0,False,The Zombies,57,1078624,"baroque pop, psychedelic rock",1Sv2t548jDyfBDgvVzYJzw,Begin Here,1965-04-30,14,album,2.42

In [41]:
df1

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8577,0AQquaENerGps8BQmbPw14,Big Iron,1,71,False,Marty Robbins,60,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,3.92
8578,4f8hBeMXMvssn6HtFAtblo,El Paso,10,64,False,Marty Robbins,61,626733,"classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,15,album,4.32
8579,0Vy7wsXNFrbNc6UTWoScnM,Over the Rainbow,5,8,False,The Mystics,27,18184,doo-wop,2ifB9Xjp9DdpqLlYlY60QW,Presenting The Mystics,1959-02-11,9,compilation,2.28
8580,760clbeDBWmBsBLbszWuNZ,I'm A Man,2,55,False,Bo Diddley,44,333376,"blues, classic blues, rock and roll, rockabilly",1cbtDEwxCjMhglb49OgNBR,Bo Diddley,1958-01-01,12,album,2.74
8581,61GEP8lryEfcuEgBMbRmNi,Alone And Forsaken,11,45,False,Hank Williams,55,1067339,"classic country, honky tonk, traditional count...",3cusZESjkIDnDXyQwbpSsT,Moanin' The Blues (Expanded Edition),1952-09-12,12,album,2.02

In [42]:
artist_name=df1.pivot_table(index="artist_name", values="artist_followers", aggfunc=["min", "max", "mean"])
artist_name

                              min              max             mean
                 artist_followers artist_followers artist_followers
artist_name
$uicideboy$               8957416          8957416        8957416.0
'Ery Noice                  11720            11720          11720.0
(((())))                    49519            49519          49519.0
*NSYNC                    3088613          3088613        3088613.0
-                             714              714            714.0
...                           ...              ...              ...
攬佬SKAI ISYOURGOD           298654           298654         298654.0
時瀬高等学校箏曲部                    2625             2625           2625.0
桑原まこ                          346              346            346.0
梶浦 由記                      132111           132111         132111.0
藤澤慶昌                        13564            13575          13569.5

[2547 rows x 3 columns]

In [43]:
track_name=df1.pivot_table(index="track_name", values="track_popularity", aggfunc=["min", "max", "mean"])
track_name

,min,max,mean
,track_popularity,track_popularity,track_popularity
track_name,,,
!!!!!!!,17,17,17.0
"""In The Hall Of The Mountain King"" from Peer Gynt Suite N°1, Op. 46",52,52,52.0
#GETITRIGHT,44,44,44.0
#thatPOWER,67,67,67.0
&burn (with Vince Staples),56,59,57.5
...,...,...,...
臨界,34,34,34.0
英雄,27,27,27.0
落葉船,38,38,38.0
道は続く,38,38,38.0
銀髪の少年,0,0,0.0

In [44]:
album_type=df1.pivot_table(index="album_type", values="track_popularity", aggfunc=["min","max","mean"])
album_type

                         min              max             mean
            track_popularity track_popularity track_popularity
album_type
album                      0               99        55.653459
compilation                0               82        40.512821
single                     0               95        46.354082

In [45]:
album_name=df1.pivot_table(index="album_name",values="album_total_tracks", aggfunc=["min","max","mean"])
album_name

,min,max,mean
,album_total_tracks,album_total_tracks,album_total_tracks
album_name,,,
#000000 & #FFFFFF (No DJ Version),16,16,16.0
#1s ... and then some,30,30,30.0
#3,10,10,10.0
#3 Deluxe Version,17,17,17.0
#willpower,15,15,15.0
...,...,...,...
この音とまれ!～時瀬高等学校箏曲部～,12,12,12.0
ソードアート・オンライン ミュージックコレクション,131,131,131.0
七つの大罪 オリジナル・サウンドトラック 2,25,25,25.0
八方來財(Stacks from All Sides),19,19,19.0
千と千尋の神隠し サウンドトラック,21,21,21.0